### ISSUE TITLE
issue with copy() methods and relative paths (powershell)

### ISSUE THREAD

**Issue by mgaruccio** [alphaleonis/AlphaFS#223]
When using the Alphaleonis.win32.filesystem.directory.copy() method and a relative path the path is calculated based on where the host was launched from rather than the scripts current working directory.   So if the powershell console is opened by itself and initially loads to c:\windows\system32 every time a relative path is used it will be calculated relative to c:\windows\system32, regardless of what the current working directory is.  oddly enough it seems to be calculating the source path works correctly but the destination fails. An example of this is shown in the screenshot attached.

![alphafs issue](https://cloud.githubusercontent.com/assets/3801085/14827657/68989f10-0bb1-11e6-9055-f27812f501bd.PNG)

Note that the same issue is present with the filesystem.file.copy() method.

**Comment by Yomodo** [comment]
@mgaruccio A number of issues have been fixed. Could you test again with the latest build?

**Comment by mgaruccio** [comment]
Happy to test, but is there a new release I'm missing? My original testing was done with 2.0.1, which appears to be the version currently hosted on GitHub.

**Comment by Yomodo** [comment]
Sorry, with the latest build I mean the developer-build.

**Comment by mgaruccio** [comment]
Looks like I'm still having the same issue after upgrading to 2.1.0
![capture](https://cloud.githubusercontent.com/assets/3801085/17743766/eebe4fd0-6472-11e6-8f07-fc7d27a58f2d.PNG)

Is there anything else I can do to assist?

**Comment by Yomodo** [comment]
Thanks, testing it on your end is already enough assisting.

Too bad it's not fixed yet. Back to the drawing board.

**Comment by Yomodo** [comment]
A PowerShell workaround would be to manually set the current directory:
`[Environment]::CurrentDirectory = "D:\Scripts"`

It seems that when using the `CD` or `Set-Location` command, the `[Environment]::CurrentDirectory` (of the PowerShell _process_) is not updated.

From the looks of it, this cannot be fixed from AlphaFS; the best practice is to use fully-qualified path names.
You can also use the Resolve-Path cmdlet to get the full path.
